source = colors.conf

### MONITORS ###
source = ~/.config/hypr/configs/monitor.conf


### MY PROGRAMS ###
$terminal = kitty
$fileManager = nautilus
$menu = rofi -show drun


### AUTOSTART ###
exec-once = nm-applet
exec-once = waybar  
exec-once = swww-daemon
exec-once = blueman-applet
exec-once = swaync
exec-once = systemctl --user start hyprpolkitagent
exec-once = hypridle

### ENVIRONMENT VARIABLES ###
# See https://wiki.hyprland.org/Configuring/Environment-variables/
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24


### PERMISSIONS ###
# See https://wiki.hyprland.org/Configuring/Permissions/
# Please note permission changes here require a Hyprland restart and are not applied on-the-fly
# for security reasons

# ecosystem {
#   enforce_permissions = 1
# }

# permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow


### TAGS ###
source= ~/.config/hypr/configs/tags.conf


### LOOK AND FEEL ###
source= ~/.config/hypr/configs/looknfeel.conf


### ANIMATIONS ###
source= ~/.config/hypr/configs/UserAnimations.conf

# Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
# windowrule = rounding 0, floating:0, onworkspace:w[tv1]
# windowrule = bordersize 0, floating:0, onworkspace:f[1]
# windowrule = rounding 0, floating:0, onworkspace:f[1]


### WINDOWRULES AND LAYERRULES ###
source = ~/.config/hypr/configs/windowrules.conf

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    new_status = master
}

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
    vfr = true # save resources
}

render {
	new_render_scheduling = true
}

### INPUT ###
source= ~/.config/hypr/configs/input.conf


### KEYBINDS ###
source= ~/.config/hypr/configs/keybinds.conf


